name: sass
version: 0.0.0
description: A Sass implementation in Dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sass

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  charcode: "^1.1.0"
  source_span: "^1.0.0"
  string_scanner: "^0.1.4"

dev_dependencies:
  test: "^0.12.0"
