name: sass
version: 0.0.0
description: A Sass implementation in Dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sass

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  args: "^0.13.0"
  charcode: "^1.1.0"
  collection: "^1.1.0"
  path: "^1.0.0"
  source_span: "^1.0.0"
  string_scanner: ">=0.1.5 <2.0.0"
  tuple: "^1.0.0"

dev_dependencies:
  test: "^0.12.0"
  grinder: "^0.8.0"
  dart_style: "^0.2.9"
